Repository Inertia-Lighting/discord-bot, pull requests merged in 2021-07, with the labels that each got.

#90 Draft: Reworked Command Permissions System
  .env.example
  .eslintrc.js
  package-lock.json
  package.json
  src/bot/commands/ban.js
  src/bot/commands/blacklist.js
  src/bot/commands/check_db.js
  src/bot/commands/echo.js
  src/bot/commands/echo_into_channel.js
  src/bot/commands/help.js
  src/bot/commands/identity_token.js
  src/bot/commands/kick.js
  src/bot/commands/lookup.js
  src/bot/commands/mute.js
  src/bot/commands/products.js
  src/bot/commands/profile.js
  src/bot/commands/quick_support.js
  src/bot/commands/reload.js
  src/bot/commands/send_embed_json.js
  src/bot/commands/support.js
  src/bot/commands/verify.js
  src/bot/commands/warn.js
  src/bot/common/bot.js
  src/bot/handlers/command_handler.js
Labels: documentation, enhancement, help wanted

#82 Logging Moderation Actions to database and `moderation_actions` command
  .env.example
  .eslintrc.js
  package-lock.json
  package.json
  src/bot/commands/ban.js
  src/bot/commands/kick.js
  src/bot/commands/moderation_actions.js
  src/bot/commands/mute.js
  src/bot/commands/warn.js
  src/bot/handlers/log_moderation_action_handler.js
  start_bot.bat
Labels: documentation, enhancement

#93 Added more quick support topics
  src/bot/commands/quick_support.js
Labels: enhancement

#96 Fixes #95
  src/server/v1/user/products/purchase.js
Labels: documentation, enhancement, help wanted

#99 Blacklist System Overhaul
  src/bot/commands/blacklist.js
  src/server/v1/auth/keys/generate.js
  src/server/v1/user/products/fetch.js
Labels: bug, documentation, enhancement, help wanted
