Repository Inertia-Lighting/discord-bot, pull requests merged in 2021-09, with the labels that each got.

#124 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement, help wanted

#119 Update command cooldown message
  src/bot/handlers/command_handler.js
Labels: enhancement

#117 Added purge command
  src/bot/commands/purge.js
Labels: documentation, enhancement

#129 fixes(#115)
  src/server/v1/user/verification/verify.js
Labels: bug, documentation, enhancement

#133 fixes(#125)
  src/server/server.js
  src/server/v1/auth/tokens/test.js
Labels: enhancement

#132 fixes(#127)
  src/bot/commands/support.js
Labels: enhancement

#141 Fixes(#140)
  .env.example
  src/bot/handlers/welcome_message_handler.js
Labels: bug
