Repository Inertia-Lighting/discord-bot, pull requests merged in 2021-06, with the labels that each got.

#72 feat: Welcome Message for new members
  src/bot/events/guild_member_add.js
  src/bot/handlers/welcome_message_handler.js
Labels: documentation, enhancement

#74 Added ESLint
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/bot/commands/blacklist.js
  src/bot/commands/help.js
  src/bot/commands/identity_token.js
  src/bot/commands/mute.js
  src/bot/commands/products.js
  src/bot/commands/quick_support.js
  src/bot/commands/reload.js
  src/bot/commands/support.js
  src/bot/commands/verify.js
  src/bot/handlers/suggestions_category_handler.js
  src/bot/handlers/welcome_message_handler.js
  src/server/v1/auth/keys/generate.js
  src/server/v1/products/fetch/fetch.js
  src/utilities.js
Labels: dependencies, documentation, enhancement, help wanted

#69 Improvements to support system
  src/bot/commands/support.js
Labels: documentation, enhancement

#63 added kick command
  src/bot/commands/kick.js
  start_bot.bat
Labels: documentation, enhancement

#78 Ban command
  src/bot/commands/ban.js
Labels: documentation, enhancement

#81 Support Ticket System & Command: fixes and cleanup
  .env.example
  src/bot/bot.js
  src/bot/commands/support.js
  src/bot/events/ready.js
Labels: bug, documentation, enhancement, help wanted
